spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: testdb
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
    
logging:
  level:
    root: ERROR
    org: ERROR
    
customersURL: http://localhost:8092
productsURL: http://localhost:8091    