spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: testdb

logging:
  level:
    root: ERROR
    org: ERROR
    
ordersURL: http://localhost:8094
productsURL: http://localhost:8091